### ISSUE TITLE
BUG: Error: Expected Connection: upgrade with browser.

### ISSUE THREAD

**Issue by houd1ni** [JuliaWeb/HTTP.jl#370] opened 2018-12-18 20:14 UTC
Julia 1.0.2
HTTP.jl 0.7.0
MbedTLS.jl ???

Hello, I've faced an issue when connection from native Firefox method https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

```
Error: (HTTP.WebSockets.WebSocketError(0, "Expected \"Connection: upgrade\"!\nHTTP.Messages.Request:\n\"\"\"\nGET
/ HTTP/1.1\r\nHost: localhost:8001
```

I've made a little research:
```

function check_upgrade(http)

  println(99, http)  # Connection: keep-alive, Upgrade is in list.
    hasheader(http, "Upgrade", "websocket"),  # true
    hasheader(http, "Connection", "upgrade"), # false
    hasheader(http, "Connection", "keep-alive, Upgrade")  # true
)

```

then I've replaced next line ```   if !hasheader(http, "Connection", "upgrade") ``` to ```  if false && !hasheader(http, "Connection", "upgrade") ``` tested connection with some data and so. It works!

So, I concluded, that the problem is in `hasheader` method. More specifically, in its' comma splitting.

**Comment by Hugo-Trentesaux** [comment] 2018-12-31 12:30
I created a PR: https://github.com/JuliaWeb/HTTP.jl/pull/374

**Comment by houd1ni** [comment] 2019-01-01 15:09
@Hugo-Trentesaux  merci becaoup! I made own fork to workaround and then made some other changes to have more agile websockets: https://github.com/houd1ni/HTTP.jl

If I have time, I'll try to merge changes and make a PR with other changes.

**Comment by Hugo-Trentesaux** [comment] 2019-01-01 18:19
I looked at your commits, I do not understand why you changed the name from HTTP to HTTPA. I do not understand either what makes your websocket more "agile". Could you please give further explanation?

**Comment by CarpeNecopinum** [comment] 2019-01-09 09:35
Looks to me like a duplicate of #320 

This should be fixed by #321 already. The version you're running (HTTP.jl 0.7) doesn't have that fix though, you'll have to use master.

**Comment by houd1ni** [comment] 2019-01-09 12:08
@CarpeNecopinum  thanks! Is it in Pkg registry already?

**Comment by quinnj** [comment] 2019-01-23 05:20
We'll be releasing a new version tonight, so I'll close this for now.

**Closed by quinnj** 2019-01-23 05:20 UTC
