### ISSUE TITLE
verbose string reports wrong port number

### ISSUE THREAD

**Issue by clarkevans** [JuliaWeb/HTTP.jl#650] opened 2020-12-21 17:52 UTC
Julia 1.5.3
HTTP.jl 0.8.19

If I use `HTTP.serve(ROUTER, server=mysocket, verbose=true)` and if `mysocket` is listening on a port other than 8081, it reports 8081 anyway in the log message.

**Comment by fredrikekre** [comment] 2021-09-30 10:24
Duplicate of #610, fixed by  #611.

**Closed by fredrikekre** 2021-09-30 10:24 UTC
