### ISSUE TITLE
help stresstesting websockets?

### ISSUE THREAD

**Issue by zahachtah** [JuliaWeb/HTTP.jl#336] opened 2018-10-16 17:46 UTC
Julia 1.0.1
HTTP.jl v0.6.14 
MbedTLS.jl 0.6.3 -- Please specify versions

So I am interested in seeing how many agents can interact with a simulation I am running. I set up this very simple (or so I thought) script to do that (actual algorithms are not there yet). For some reason I cannot figure out why only a maximum of 8 agents actually start up and interact with the server even if the loop initiates 16 (or more). Any idea?

```julia
using HTTP,JSON
using HTTP: hasheader
using HTTP.IOExtras, HTTP.Sockets
using MbedTLS

function agent(port,number)
 HTTP.WebSockets.open("ws://127.0.0.1:$port") do ws
     @async while !eof(ws) #receiving data
         data = readavailable(ws)
         println("roundtrip from: "*String(data))
     end
    while true #sending data
        sleep(1.0)
        write(ws, string(number))
    end
 end
end

function server(port)
   @async HTTP.listen(Sockets.localhost, port) do http
       if HTTP.WebSockets.is_upgrade(http.message)
           HTTP.WebSockets.upgrade(http) do ws
               while !eof(ws)
                   data = readavailable(ws)
                   write(ws, data)
                   #println("S: got "*String(data))
               end
           end
       end
   end
end

server(9999)

sleep(2.0)

for i in 1:16
    sleep(1.0)
    @async agent(9999,i)
end
```

**Comment by Hugo-Trentesaux** [comment] 2019-01-01 20:38
If I run this code for a minute, I get an `ArgumentError: stream is closed or unusable`. Do you know how to prevent the socket from closing ?

**Comment by samoconnor** [comment] 2019-02-14 02:53
Limit of 8 connections: https://github.com/JuliaWeb/HTTP.jl/blob/a38358367af3b0b5ae185583af6c2a594245acb2/src/HTTP.jl#L94

Close after 1 minute probably caused by #341 ?

**Closed** 2020-10-09 05:51 UTC
Labels: websockets
