### ISSUE TITLE
Deadlock with https requests

### ISSUE THREAD

**Issue by kcajf** [JuliaWeb/HTTP.jl#771] opened 2021-09-27 17:07 UTC
On my linux machine, this deadlocks 100% of the time:
```
function f(N)
    @sync for _ in 1:N
        Threads.@spawn HTTP.get("https://google.com")
    end
end
f(9)
```

If I set N=8, there is no deadlock. I have `JULIA_NUM_THREADS = 8`. If I use `http` instead of `https`, there is no deadlock, suggesting the problem is in some HTTPS-related code.

It would be great if someone could attempt to reproduce this.

Julia 1.6.1
HTTP.jl 0.9.15
MbedTLS.jl 1.0.3

**Comment by fredrikekre** [comment] 2021-09-30 09:44
> It would be great if someone could attempt to reproduce this.

I can't.

**Comment by kcajf** [comment] 2021-09-30 10:08
Some further mystery - it seems to always occur on the 8/9 boundary irrespective of `JULIA_NUM_THREADS`. I set `JULIA_NUM_THREADS` to 1 and 3, and N=9 was still the breaking point. My machine has 8 threads (i.e. `Sys.CPU_THREADS == 8`).

**Comment by fredrikekre** [comment] 2021-09-30 10:14
Okay, I tried with 4/5 on a machine with 4 threads. The magic 8 number shows up here: https://github.com/JuliaWeb/HTTP.jl/blob/edf81a03d1cb03a6c205391890edb11e9b7009ff/src/ConnectionPool.jl#L37 (see https://github.com/JuliaWeb/HTTP.jl/issues/743)

**Comment by kcajf** [comment] 2021-09-30 10:19
Well spotted, thanks. Changing that number changes the deadlock point, so it is definitely the culprit here.

**Comment by fredrikekre** [comment] 2021-09-30 13:37
I can't reproduce on a 4 threads machine even if I change that number to 4. In any case, I guess some locking logic is wrong here: https://github.com/JuliaWeb/HTTP.jl/blob/edf81a03d1cb03a6c205391890edb11e9b7009ff/src/ConnectionPool.jl#L547-L588

Does `verbose=2` or `verbose=3` give any insight?

**Comment by kcajf** [comment] 2021-09-30 14:32
It didn't give much useful output, other than reminding me that I am going through a web proxy. 

This seems to go via a different code path:
https://github.com/JuliaWeb/HTTP.jl/blob/edf81a03d1cb03a6c205391890edb11e9b7009ff/src/ConnectionRequest.jl#L97
and then
https://github.com/JuliaWeb/HTTP.jl/blob/edf81a03d1cb03a6c205391890edb11e9b7009ff/src/ConnectionPool.jl#L749

I'm not familiar with the codebase but does this give you a clue?

**Comment by fredrikekre** [comment] 2021-09-30 14:34
> I am going through a web proxy

Okay, I am not so thats probably related then.

> I'm not familiar with the codebase but does this give you a clue?

Me neither, just trying to pin point the problem. Maybe @quinnj can have a look.

**Comment by kcajf** [comment] 2021-10-05 08:56
A bit of fiddling shows the deadlock is happening here: https://github.com/JuliaWeb/HTTP.jl/blob/edf81a03d1cb03a6c205391890edb11e9b7009ff/src/ConnectionPool.jl#L575

i.e. threads are left waiting forever on `take!(pod.conns)`. Connections are never being returned to the pod.

The doc for this function seems relevant - https proxy tunnel upgrades shouldn't get re-used. 
https://github.com/JuliaWeb/HTTP.jl/blob/edf81a03d1cb03a6c205391890edb11e9b7009ff/src/ConnectionPool.jl#L509

And I can confirm that [this line](https://github.com/JuliaWeb/HTTP.jl/blob/edf81a03d1cb03a6c205391890edb11e9b7009ff/src/ConnectionPool.jl#L511) is evaluating to true for proxied HTTPS requests and false for proxied HTTP requests - the HTTPS requests don't get returned to the pod ([this branch](https://github.com/JuliaWeb/HTTP.jl/blob/edf81a03d1cb03a6c205391890edb11e9b7009ff/src/ConnectionPool.jl#L499) evaluates to false). 

I don't know much about any of this but it seems that, if these connections can't be re-used, there needs to be some logic in `getconnection` to create new proxied connections? @quinnj are you able to take a look please?

**Comment by kcajf** [comment] 2022-01-04 14:21
I'm still able to reproduce this on version 0.19.7. I hadn't realised that I could set `connection_limit` in HTTP.get itself - changing that number also changes the `N` at which deadlock occurs.

**Comment by kcajf** [comment] 2022-01-04 14:25
Another clarification: this also happens with `@async` instead of `Threads.@spawn`.

**Comment by kcajf** [comment] 2022-01-04 14:45
I'm embarrassed that I didn't try this before commenting but: it looks like this is fixed on master! I see @quinnj that you made a lot of changes to pooling / pipelining in #783, so that must have fixed or removed this deadlock. Thank you! Looking forward to the next release.

**Comment by fredrikekre** [comment] 2022-01-10 13:13
Nice, I will close this then.

**Closed by fredrikekre** 2022-01-10 13:13 UTC

**Comment by quinnj** [comment] 2022-01-11 04:35
Yes, that's very good to hear. We were making a push for a new 1.0 release before the (U.S.) holidays, but things kind of stalled out. I'm going to try and push again on that this week, so it's great to hear people trying things out on master.
