### ISSUE TITLE
Bugged code?

### ISSUE THREAD

**Issue by louisponet** [JuliaWeb/HTTP.jl#800] opened 2022-02-09 13:30 UTC
While browsing through the code to investigate some invalidations @timholy and I came across this part:

https://github.com/JuliaWeb/HTTP.jl/blob/46687c8e594cbde40cdcfa63fe66123ebad1ea5c/src/IODebug.jl#L15-L26

Does that code ever get used, and is it valid?
It is sadly not involved with the invalidations though.

Cheers

**Comment by fredrikekre** [comment] 2022-02-09 13:32
Basically duplicate of https://github.com/JuliaWeb/HTTP.jl/issues/712

**Comment by louisponet** [comment] 2022-02-09 13:43
Well, the invalidations part yes, the part about this branch not being executable I don't see being mentioned before. Of course if the debug code will be taken out then this solves itself :)

**Closed** 2022-05-10 12:19 UTC
