### ISSUE TITLE
Ambiguity detected for write(::IODebug, x)

### ISSUE THREAD

**Issue by Roger-luo** [JuliaWeb/HTTP.jl#759] opened 2021-09-17 00:31 UTC
When I try to add [Aqua](https://github.com/JuliaTesting/Aqua.jl/) test [IBMQClient](https://github.com/QuantumBFS/IBMQClient.jl) it reports that this line causes ambiguity to Base methods that define as `Base.write(::IO, ::Rational)` etc. when the `IO` argument is `IODebug`

https://github.com/JuliaWeb/HTTP.jl/blob/81ac5042dd284dc0525702982f71683b2e168046/src/IODebug.jl#L30

I'm not sure how to fix this, but I'd like to have Aqua test pass on my package that depends on HTTP, any idea?

**Comment by fredrikekre** [comment] 2021-09-30 10:15
Duplicate of  #712.

**Closed by fredrikekre** 2021-09-30 10:15 UTC
