### ISSUE TITLE
MethodErrror on DNSError

### ISSUE THREAD

**Issue by KristofferC** [JuliaWeb/HTTP.jl#95] opened 2017-10-12 12:22 UTC
`ERROR: MethodError: no method matching associate!(::MbedTLS.SSLContext, ::Base.DNSError)`

Not sure if this is a problem in `MbedTLS`

```
ERROR (unhandled task failure): DNSError: api.github.com, temporary failure (EAI_AGAIN)
Stacktrace:
 [1] getaddrinfo(::String) at ./socket.jl:649
 [2] (::HTTP.##37#38{HTTP.https,SubString{String},Nullable{Int64}})() at ./task.jl:335
ERROR: MethodError: no method matching associate!(::MbedTLS.SSLContext, ::Base.DNSError)
Closest candidates are:
  associate!(::MbedTLS.SSLContext, ::TCPSocket) at /home/kristoffer/.julia/v0.6/MbedTLS/src/MbedTLS.jl:100
Stacktrace:
 [1] initTLS!(::Type{HTTP.https}, ::SubString{String}, ::HTTP.RequestOptions, ::Base.DNSError) at /home/kristoffer/.julia/v0.6/HTTP/src/client.jl:186
 [2] getconn(::Type{HTTP.https}, ::HTTP.Client{Base.TTY}, ::String, ::HTTP.RequestOptions, ::Bool) at /home/kristoffer/.julia/v0.6/HTTP/src/client.jl:164
 [3] #request#34(::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at /home/kristoffer/.julia/v0.6/HTTP/src/client.jl:116
 [4] (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at ./<missing>:0
 [5] request(::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions, ::HTTP.Connection{MbedTLS.SSLContext}, ::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool) at /home/kristoffer/.julia/v0.6/HTTP/src/client.jl:230
 [6] #request#34(::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at /home/kristoffer/.julia/v0.6/HTTP/src/client.jl:116
 [7] (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at ./<missing>:0
 [8] #request#32(::Dict{String,String}, ::String, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Method, ::HTTP.URI) at /home/kristoffer/.julia/v0.6/HTTP/src/client.jl:98
 [9] (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Method, ::HTTP.URI) at ./<missing>:0
 [10] #get#46(::Bool, ::Array{Any,1}, ::Function, ::HTTP.URI) at /home/kristoffer/.julia/v0.6/HTTP/src/client.jl:436
 [11] (::HTTP.#kw##get)(::Array{Any,1}, ::HTTP.#get, ::HTTP.URI) at ./<missing>:0
[...]
```

**Comment by quinnj** [comment] 2017-10-13 02:47
Can you reproduce this? It'd be nice if you could try on latest master since the client-side error handling has been completely revamped. I just need to clean up a few things and do a new tag; I've mainly been waiting on improving the precompile situation a bit, but it's not too bad anymore.

**Comment by quinnj** [comment] 2017-10-19 03:28
I'm pretty sure this is fixed on the latest release; definitely re-open if you see anything fishy.

**Closed by quinnj** 2017-10-19 03:28 UTC
