### ISSUE TITLE
Connecting to local network: RetryException

### ISSUE THREAD

**Issue by evanfields** [JuliaWeb/HTTP.jl#40] opened 2017-03-30 00:15 UTC
I can access a device on my home network using Requests.jl, but not HTTP.jl. Possibly a configuration issue? 

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using HTTP, Requests

julia> Requests.get("http://192.168.0.100")
Response(200 OK, 5 headers, 134 bytes in body)

julia> Requests.get("http://192.168.0.100:80")
Response(200 OK, 5 headers, 134 bytes in body)

julia> HTTP.get("http://192.168.0.100")
ERROR: RetryException: # of allowed retries (3) was exceeded when making request
 in request(::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions, ::HTTP.Connection{TCPSocket}, ::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:224
 in #request#34(::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:114
 in (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at .\<missing>:0
 in request(::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions, ::HTTP.Connection{TCPSocket}, ::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:225
 in #request#34(::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:114
 in (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at .\<missing>:0
 in request(::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions, ::HTTP.Connection{TCPSocket}, ::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:225
 in #request#34(::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:114
 in (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at .\<missing>:0
 in #request#32(::Dict{String,String}, ::HTTP.FIFOBuffer, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Method, ::HTTP.URI) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:98
 in (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Method, ::HTTP.URI) at .\<missing>:0
 in #get#51(::Bool, ::String, ::Array{Any,1}, ::Function, ::String) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:424
 in get(::String) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:424

julia> HTTP.get("http://192.168.0.100:80")
ERROR: RetryException: # of allowed retries (3) was exceeded when making request
 in request(::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions, ::HTTP.Connection{TCPSocket}, ::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:224
 in #request#34(::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:114
 in (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at .\<missing>:0
 in request(::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions, ::HTTP.Connection{TCPSocket}, ::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:225
 in #request#34(::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:114
 in (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at .\<missing>:0
 in request(::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions, ::HTTP.Connection{TCPSocket}, ::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:225
 in #request#34(::Array{HTTP.Response,1}, ::Int64, ::Bool, ::Bool, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:114
 in (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at .\<missing>:0
 in #request#32(::Dict{String,String}, ::HTTP.FIFOBuffer, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Method, ::HTTP.URI) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:98
 in (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Method, ::HTTP.URI) at .\<missing>:0
 in #get#51(::Bool, ::String, ::Array{Any,1}, ::Function, ::String) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:424
 in get(::String) at C:\Users\Evan\.julia\v0.5\HTTP\src\client.jl:424
```

**Comment by quinnj** [comment] 2017-04-06 03:45
@evanfields, what kind of server do you have listening on your local ip?

**Comment by quinnj** [comment] 2017-04-06 04:02
I ask because if I start up a julia HTTP server listening locally, I can access it via `HTTP.get("http://127.0.0.1:8081")` and the server response just fine. However, if I try to use my local ip, I get `ERROR: connect: connection refused (ECONNREFUSED)` errors for both HTTP and Requests.

I'm just trying to better understand your setup and how things are getting routed.

**Comment by evanfields** [comment] 2017-04-07 14:07
The device I'm trying to access is a Phillips Hue bridge. It's just plugged into my home router, and the router assigned it IP address `192.168.0.100`. I.e. the server I'm trying to reach is not on the same machine hosting the client.

**Comment by quinnj** [comment] 2017-05-06 18:45
Sorry for the slowness in responding here but I'm struggling to figure out exactly how to reproduce this in order to debug what's going on. If you have any suggestions, I'd appreciate it.

**Comment by samoconnor** [comment] 2017-07-14 06:24
Hi @quinnj,

I noticed a few places in the code where `catch` is used without checking the type of the exception: https://github.com/JuliaWeb/HTTP.jl/search?q=catch

I'm not sure if it would help for this issue, but I would suggest explicitly testing for the expected exception type and re-throwing any unexpected exceptions. In my experience, doing this makes things much easier to debug. e.g. consider:

```julia
function f(conn)
    try
        return readavailable(conn.tcp)
    catch e
        println("IO-related error")
    end
end

julia> f(7)
IO-related error
```

vs

```julia
function f(conn)
    try
        return readavailable(conn.tcp)
    catch e
        if isa(e, IOError)
            println("IO-related error")
        else
            rethrow(e)
        end
    end
end
```

or

```julia
using Retry
function f(conn)
    @protected try
        return readavailable(conn.tcp)
    catch e
        @ignore if isa(e, IOError) println("IO-related error") end
    end
end

julia> f(7)
ERROR: type Int64 has no field tcp
```

**Comment by quinnj** [comment] 2017-08-25 11:52
@evanfields, would you be willing to try your original example out again on latest HTTP.jl master? We've recently done a pretty big overhaul of the client-side error-handling and request/response reading/writing, so I'm confident we can at least get a better error message in the case you ran into.

**Comment by evanfields** [comment] 2017-08-26 00:18
Sure. The good news is this works now! Code:
```
Pkg.status("HTTP")
using HTTP
using Requests

r_http = HTTP.get("http://192.168.0.100")
println("HTTP body:")
println(String(read(r_http.body)))

r_requests = Requests.get("http://192.168.0.100")
println("Requests body:")
println(String(r_requests.data))
```

Result (scrubbing endless Compat warnings from Requests):
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> include("C:\\Users\\ejfie\\Desktop\\http_test.jl")
 - HTTP                          0.4.3+             master
WARNING: Method definition (::Type{Base.Val{T} where T})(Any) in module Handlers at C:\Users\ejfie\.julia\v0.6\HTTP\src\handlers.jl:56 overwritten in module Compat at C:\Users\ejfie\.julia\v0.6\Compat\src\Compat.jl:463.
HTTP body:
<html><head><title>hue personal wireless lighting</title></head><body><b>Use a modern browser to view this resource.</b></body></html>
Requests body:
<html><head><title>hue personal wireless lighting</title></head><body><b>Use a modern browser to view this resource.</b></body></html>
```

The bad news is that `println(r_http)` prints the following then seems to hang forever:
```
julia> println(r_http)
HTTP.Response:
"""
HTTP/1.1 200 OK
Content-Type: text/html
```

(Lastly I'll note / say thanks that on master a different bug seems to have been fixed. The same get request from HTTP and Requests was giving me 132 characters on HTTP latest (not master), and ~1000 on Requests. I assumed that was a server problem like #36, but I guess not since with HTTP master the response bodies are the same. Yippee for progress.)

**Comment by quinnj** [comment] 2017-08-26 04:45
Hmmm, can you post the exact steps to reproduce the hang? I can't seem to reproduce trying a few different things locally.

**Comment by evanfields** [comment] 2017-08-26 11:22
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 1600X Six-Core Processor
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Barcelona)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, generic)

julia> using HTTP

julia> HTTP.get("192.168.0.100")
HTTP.Response:
"""
HTTP/1.1 200 OK
Content-Type: text/html

**Comment by quinnj** [comment] 2017-08-26 13:23
Ok, just pushed a fix. Can you try again after running `Pkg.checkout("HTTP")`?

**Comment by evanfields** [comment] 2017-08-26 18:44
I'm away from a Julia running computer for a few days but I'll edit this comment when I'm back next week.

**Comment by evanfields** [comment] 2017-08-30 16:31
Latest master fixes the printing hang:

```
julia> Pkg.checkout("HTTP")
INFO: Checking out HTTP master...
INFO: Pulling HTTP latest master...
INFO: No packages to install, update or remove

julia> using HTTP
INFO: Recompiling stale cache file C:\Users\ejfie\.julia\lib\v0.6\HTTP.ji for module HTTP.

julia> r = HTTP.get("192.168.0.100");

julia> r
HTTP.Response:
"""
HTTP/1.1 200 OK
Content-Type: text/html

[open HTTP.FIFOBuffer with 134 bytes to read]
"""

julia> String(read(r.body))
"<html><head><title>hue personal wireless lighting</title></head><body><b>Use a modern browser to view this resource.</b></body></html>"

julia> r
HTTP.Response:
"""
HTTP/1.1 200 OK
Content-Type: text/html

[open HTTP.FIFOBuffer with 0 bytes to read]
"""
```

**Closed** 2017-08-30 23:37 UTC
