### ISSUE TITLE
Broken pipe when trying to create a simple server with SSL

### ISSUE THREAD

**Issue by nlw0** [JuliaWeb/HTTP.jl#491] opened 2020-01-02 11:07 UTC
Julia 1.4.0-DEV.375
  [cd3eb016] HTTP v0.8.8
  [739be429] MbedTLS v0.7.0

I'm trying to run a modified version of the example server code with SSL. This is my code:

```
using HTTP
using MbedTLS

HTTP.serve(sslconfig=MbedTLS.SSLConfig("host.cert", "host.key")) do request::HTTP.Request
   @show request
   @show request.method
   @show HTTP.header(request, "Content-Type")
   @show HTTP.payload(request)
   try
       return HTTP.Response("Hello")
   catch e
       return HTTP.Response(404, "Error: $e")
   end
end
```

This is the result when I try to make a request:
```
julia> include("/home/user/src/CaliFind.jl/web/jlserve.jl");
ERROR: LoadError: IOError: write: broken pipe (EPIPE)
Stacktrace:
 [1] uv_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:953
 [2] unsafe_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:1007
 [3] f_send(::Ptr{Nothing}, ::Ptr{UInt8}, ::UInt64) at /home/user/.julia/packages/MbedTLS/a1JFn/src/ssl.jl:255
 [4] ssl_handshake(::MbedTLS.SSLContext) at /home/user/.julia/packages/MbedTLS/a1JFn/src/ssl.jl:606
 [5] handshake(::MbedTLS.SSLContext) at /home/user/.julia/packages/MbedTLS/a1JFn/src/ssl.jl:74
 [6] handshake! at /home/user/.julia/packages/MbedTLS/a1JFn/src/MbedTLS.jl:141 [inlined]
 [7] getsslcontext(::Sockets.TCPSocket, ::SSLConfig) at /home/user/.julia/packages/HTTP/lZVI1/src/Servers.jl:87
 [8] listenloop(::Function, ::HTTP.Servers.Server{SSLConfig,Sockets.TCPServer}, ::HTTP.Servers.var"#2#5"{Nothing,HTTP.Servers.var"#4#7"}, ::Base.RefValue{Int64}, ::Int64, ::Int64, ::Bool) at /home/user/.julia/packages/HTTP/lZVI1/src/Servers.jl:81
 [9] listen(::HTTP.Handlers.var"#4#5"{HTTP.Handlers.RequestHandlerFunction{var"#9#10"}}, ::Sockets.IPv4, ::Int64; sslconfig::SSLConfig, tcpisvalid::Function, server::Nothing, reuseaddr::Bool, connection_count::Base.RefValue{Int64}, rate_limit::Nothing, reuse_limit::Int64, readtimeout::Int64, verbose::Bool) at /home/user/.julia/packages/HTTP/lZVI1/src/Servers.jl:232
 [10] serve(::Function, ::Sockets.IPv4, ::Int64; stream::Bool, kw::Base.Iterators.Pairs{Symbol,SSLConfig,Tuple{Symbol},NamedTuple{(:sslconfig,),Tuple{SSLConfig}}}) at /home/user/.julia/packages/HTTP/lZVI1/src/Handlers.jl:345
 [11] top-level scope at /home/user/src/CaliFind.jl/web/jlserve.jl:4
 [12] include(::String) at ./client.jl:447
 [13] top-level scope at REPL[3]:1
in expression starting at /home/user/src/CaliFind.jl/web/jlserve.jl:4

julia> 
```

I cannot figure out if this is a bug or a feature. Is there a way I can test my key?

**Comment by benelsen** [comment] 2020-01-02 15:01
Are you using a self-signed cert for the server?
I believe what happens here is that your client closes the connection once it sees the untrusted certificate which makes HTTP.jl/MbedTLS.jl error on a broken pipe.
I was able to reproduce this HTTP.jl as a client, and once I tell them to trust the cert (either not verifying or giving it the corresponding CA cert) it works.
```julia
julia> HTTP.get("https://localhost:8081/", sslconfig=MbedTLS.SSLConfig(false), retry = false)
```
or
```julia
julia> sc = MbedTLS.SSLConfig(true)
julia> ca = MbedTLS.crt_parse_file("ca.cert.pem")
julia> MbedTLS.ca_chain!(sc, ca)
julia> HTTP.get("https://localhost:8081/", sslconfig=sc, retry = false)
```
I would consider this a bug, the server shouldn't stop working because a client doesn't trust it.

**Comment by nlw0** [comment] 2020-01-06 08:01
Yes, it's self-signed. I think I didn't even see the warning message on Chrome, though.

**Comment by quinnj** [comment] 2020-10-09 03:58
Duplicate of https://github.com/JuliaWeb/HTTP.jl/issues/318; fix incoming

**Closed by quinnj** 2020-10-09 03:58 UTC
