### ISSUE TITLE
Content-Type charset ISO-8859-1

### ISSUE THREAD

**Issue by TotalVerb** [JuliaWeb/HTTP.jl#38] opened 2017-03-17 16:51 UTC
For example,

```julia
julia> take!(String, HTTP.get("http://google.com"))
[ truncated either error while showing string (0.5) or string of invalid UTF-8 data (0.6) ]

julia> using StringEncodings

julia> decode(take!(HTTP.get("http://google.com")), enc"ISO-8859-1")
[ truncated correct source code of Google.com ]
```

Because the HTTP header contains

```
Content-Type: text/html; charset=ISO-8859-1
```

it should be possible to detect the correct encoding and decode it automatically.

**Comment by quinnj** [comment] 2017-04-04 02:32
Hmmm, it's not immediately clear what the API should be here. I mean, in your example, that's pretty clear and straightforward. The problem is we don't have an API for "getting" the body of a Response as a String, but rather we do `String(take!(resp))`. Any suggestions for how to do this automatically? @nalimilan?

**Comment by nalimilan** [comment] 2017-04-15 13:39
`decode` takes a `Vector{UInt8}` and returns a `String`, so `decode(take!(resp), enc"ISO-8859-1")` should be fine AFAICT.

**Comment by iamed2** [comment] 2017-04-25 19:55
How about a couple methods of `decode`?

```
import StringEncodings: decode, Encodings

decode{T}(response::HTTP.Response, encoding::Encodings.Encoding{T}) = decode(take!(response), encoding)

function decode(response::HTTP.Response)
    encoding = parse_encoding(response.headers["Content-Type"]; fallback="utf-8")
    decode(response, encoding)
end
```

**Comment by quinnj** [comment] 2017-04-25 20:38
Yeah, I've been thinking some approach like that should work. Care to PR?

**Comment by quinnj** [comment] 2017-08-25 12:01
Marked as "help wanted" if anyone cares to take a stab at doing this.

**Closed** 2017-11-03 04:38 UTC
Labels: help wanted

**Comment by quinnj** [comment] 2017-11-03 06:06
I added a special case and converter for ISO-8859-1; if it's detected in the Response Content-Type, we'll auto-convert when you do `String(::Response)`.
