### ISSUE TITLE
HTTPS request gets blocked while using proxy 

### ISSUE THREAD

**Issue by vdayanand** [JuliaWeb/HTTP.jl#562] opened 2020-07-27 07:00 UTC
```
http_proxy=http://127.0.0.1:3128 https_proxy=http://127.0.0.1:3128 julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.1 (2020-04-14)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
julia> using HTTP
julia> count = 0
0
julia> using HTTP

julia> while true
           global count
           count+=1
           @info "Request $count"
           HTTP.get("https://example.com")
       end
[ Info: Request 1
[ Info: Request 2
[ Info: Request 3
[ Info: Request 4
[ Info: Request 5
[ Info: Request 6
[ Info: Request 7
[ Info: Request 8 ## This gets blocked when default connection limit is 8
```

This happens only for HTTPS connections. 

Julia 1.4.1
HTTP.jl 0.8.16 
MbedTLS.jl 1.0.2
Proxy: https://hub.docker.com/r/datadog/squid/

**Comment by Teo-ShaoWei** [comment] 2020-07-29 04:20
I'm met with the same issue on the same setup as @vdayanand.

I also managed to isolate the issue to `HTTP.request` not releasing the connection upon receipt of the response, regardless of the response status and which `HTTP.request` variant we use. Here are some tests I've done, scoped and illustrated using the above code but with `HTTP.request("GET", "https://example.com", connection_limit=4)` instead:
1. In REPL, the 5th request hangs. So the issue is affected by `connection_limit`.
1. If I interrupt and re-run within the same REPL session, the 1st request hangs. So the issue is persistent across different `HTTP.request`.
1. If I end and restart another REPL session, the 5th request hangs.
1. If I run the above as a background script that hangs at the 5th request but does not terminate, a second run of the script also hangs at the 5th request. So the issue is likely on the connection count on `HTTP.jl` side.

**Comment by cflee** [comment] 2020-07-29 06:47
I noticed that there is a change #529 that landed in v0.8.14 which makes some changes to error-handling in the ConnectionPoolLayer, and it looks a bit weird for HTTPS requests.

Previously: https://github.com/JuliaWeb/HTTP.jl/blob/b9076be007337b96c73efec64c644b68d0ad48f4/src/ConnectionRequest.jl#L84-L100

Current: https://github.com/JuliaWeb/HTTP.jl/blob/abc5d3d5959db7f77e8f760226b994b3e33678e2/src/ConnectionRequest.jl#L84-L94

It seems that previously the `io` from `getconnection()` will be closed after `tunnel_request()` returns due to the finally block, but now the condition on line 92 can't be reached so it's only closed if an exception is caught.

**Comment by Teo-ShaoWei** [comment] 2020-07-29 07:18
Oh my... it worked! 🎉

I changed line 84-89 to the following:
```
if proxy !== nothing && target_url.scheme == "https"
    target_url = merge(target_url, port=443)
    r = tunnel_request(Next, io, target_url, req, body; kw...)
else
    r = request(Next, io, req, body; kw...)
end
```

I would believe this part might benefit from some refactoring to bring out the intention better.

For line 84-93, if what we want is for proxies to always close, then we might want to consider grouping by existence of HTTPS proxy:
```
if proxy !== nothing && target_url.scheme == "https"
    target_url = merge(target_url, port=443)
    r = tunnel_request(Next, io, target_url, req, body; kw...)
    close(io)
else
    r = request(Next, io, req, body; kw...)
    if io.sequence >= reuse_limit
        close(io)
    end
end
```

If actually `(proxy !== nothing && target_url.scheme == "https")` was added to the second condition due to a bugfix as it initially was part of an error correction code, and we actually don't want to always close proxied HTTPS connections, then we might want to consider:
```
if proxy !== nothing && target_url.scheme == "https"
    target_url = merge(target_url, port=443)
    r = tunnel_request(Next, io, target_url, req, body; kw...)
else
    r = request(Next, io, req, body; kw...)
end

if io.sequence >= reuse_limit
    close(io)
end
```

**Comment by Teo-ShaoWei** [comment] 2020-07-29 10:16
On further look, it might be that the additional code was to figure out some weird behaviour of why `io` wasn't closed, so it did the best effort of closing here and move on. I would believe that reclaiming of the resources should be non-throwing and properly coded as such elsewhere. So we can consider the following code too:
```
try
    if proxy !== nothing && target_url.scheme == "https"
        target_url = merge(target_url, port=443)
        return tunnel_request(Next, io, target_url, req, body; kw...)
    else
        return request(Next, io, req, body; kw...)
    end
finally
    if io.sequence >= reuse_limit
        close(io)
    end
end
```
It has a clearer intention, and spur us to fix `close` elsewhere if it could throw due to some bugs.

**Comment by Teo-ShaoWei** [comment] 2020-07-30 09:54
Sorry I was being careless, I should have read the history first to have a better understanding of the rationale myself. So I've read that:
1. We close IO on error (5aa1b0b913ed343aaf34dcbd475d71e8a5d72dd6)
1. We do not want to reuse of the connection to the HTTPS proxy (https://github.com/JuliaWeb/HTTP.jl/pull/219#discussion_r173129039)
1. We separately want to close connections above the reuse_limit (https://github.com/JuliaWeb/HTTP.jl/pull/292#discussion_r216023395, #339, #343, #346)
1. The error handling got rearranged (#529)

This is from #529:
> If we did throw an error and tried to close the connection,
there's no reason to try to do so again during the finally block.
Also, if we are in the error block, close(io) has quite a high chance
for failing, so wrap it in try to suppress such errors and instead
rethrow the original error.

Let's see... The problem is valid. Double closing in both error and final is a code smell. However, I would disagree with the solution. As I mentioned above, (and also discussed in https://github.com/JuliaWeb/HTTP.jl/pull/529#discussion_r409031183), `close` is resource destruction, and shouldn't throw an exception. In the event, `close` errored out, that is a bug and we will want to fix the implementation of our `close` instead of giving it concession and affect the correctness here. I think a better way is to challenge the implementation of closing IO inside `catch` block (5aa1b0b913ed343aaf34dcbd475d71e8a5d72dd6). We might wanted to take the chance to close IO inside a `finally` block.

I would thus recommend us to go with not closing in `catch` and only in `finally`:
```
try
    if proxy !== nothing && target_url.scheme == "https"
        target_url = merge(target_url, port=443)
        return tunnel_request(Next, io, target_url, req, body; kw...)
    else
        return request(Next, io, req, body; kw...)
    end
finally
    if (io.sequence >= reuse_limit
    || (proxy !== nothing && target_url.scheme == "https"))
        close(io)
    end
end
```

I might have under-considered the problem, so together with @vdayanand, I would like to invite the original contributors for more discussion on how to resolve this bug please. @samoconnor @Keno

**Closed** 2020-09-16 06:37 UTC
